for i in range(5)
	for j in range(5-i-1)
		print( ,end='')
	for j in range(i2+1)
		print(,end='')
	print('')
for i in range(5)
	for j in range(i)
		print( ,end='')
	for j in range(52-i2-1)
		print(,end='')
	print()